### PR TITLE
Update readme for counting

### PR DESCRIPTION
**Pull request by Max-Almighty**
Just incorporates the setcount command into the readme. Also I don't know why its taking into consideration the thing in the  setcount command, I'm still very new to github.

### CODE REVIEW

**Comment by galen8183** [comment]
> Also I don't know why its taking into consideration the thing in the setcount command, I'm still very new to github.

In brief, you're making many very small commits, every time you edit and save a file in Github, and one of these commits was included in this PR due to it being on the same [branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell).  
Contributing to projects on Github is covered in [Github](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) and [Git's](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project) documentation.  
I would highly recommend going through at least the [quickstart](https://docs.github.com/en/get-started/quickstart), as it contains pretty much everything you need to know for basic use of git.  
*I'd also recommend getting comfortable with using [command-line git](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F), as it allows you to contribute on many more platforms than just Github, but this of course isn't strictly necessary.*

**Comment by Max-Almighty** [comment]
Sweet, thanks!

**Comment by BlackWolfWoof** [comment]
I planned to redo all readmes but never started it again.
I'll probably merge this when I come home from work and then idk

**Comment by BlackWolfWoof** [comment]
Me: still not having it merged xd

**Pull request merged**
