### PR TITLE
bruh did you type them all out?

### PR DESCRIPTION
**Pull request by Spongerooski**

### CODE REVIEW

**Comment by TheHDCrafter** [comment]
Yes 🐱

**Comment by Wolveric** [comment]
Yep... pretty much what I thought when I looked at it once... 😹 Does mean users can vary the formatting, per-option though, without having to notably modify it.

**Comment by TheHDCrafter** [comment]
That was totally planned and my intention xd

**Comment by Wolveric** [comment]
There you go then... 😂

**Comment by TheHDCrafter** [comment]
XDDDDD
Idk, i'll look into re-doing some stuff for the future maybe lol

**Comment by Spongerooski** [comment]
:wat:

**Comment by MatiasMFM2001** [comment]
Even better:

```go
{{$toSend:= sdict
	"1️⃣" "Example 1"
	"2️⃣" "Example 2"
	"3️⃣" "Example 3"
	"4️⃣" "Example 4"
	"5️⃣" "Example 5"
	"6️⃣" "Example 6"
	"7️⃣" "Example 7"
	"8️⃣" "Example 8"
	"9️⃣" "Example 9"
}}

{{if eq .Message.Author.ID 204255221017214977}}
	{{with $toSend.Get .Reaction.Emoji.Name}}
		{{sendDM (cembed "color" 0xEBBF0E "title" (print $.Reaction.Emoji.Name " Autohelp") "description" .)}}
	{{end}}

	{{deleteMessageReaction nil .Reaction.MessageID .Reaction.UserID .Reaction.Emoji.Name}}
{{end}}
```

**Comment by Wolveric** [comment]
Hahaha, yes... I did have that idea, but apparently collection selections like that get notably slower than just if statements at that scale...

**Comment by MatiasMFM2001** [comment]
Wow
I get that with *lots* of entries (say 1000), but just 10?

**Comment by Wolveric** [comment]
I brought it up specifically about this, so I'd assume it may be so.

**Comment by TheHDCrafter** [comment]
HOW MANY COMMENTS REEEEE 
my inbox is exploding lol

**Comment by Wolveric** [comment]
Also, using dicts, instead of sdicts would allow for both custom and Unicode emojis, Unicode emojis having a null ID, so you can use the or statement trick,

**Comment by MatiasMFM2001** [comment]
> I brought it up specifically about this, so I'd assume it may be so.

I'll test it out, later xd

> Also, using dicts, instead of sdicts would allow for both custom and Unicode emojis, Unicode emojis having a null ID, so you can use the or statement trick,

That's true. Improves flexibility

**Comment by jo3-l** [comment]
> Hahaha, yes... I did have that idea, but apparently collection selections like that get notably slower than just if statements at that scale...

The performance impact can be ignored here. While using hash maps does add overhead (it needs to hash the key, perform modular arithmetic, and then retrieve from internal buckets) it's still extremely fast and will have essentially 0 noticeable impact at this scale (even with thousands of elements).

**Comment by Wolveric** [comment]
Good to know then. Gives you a more flexible and expandable system, for a negligible performance cost...

**Comment by Spongerooski** [comment]
I intentionally did not do that for the sake of simplicity

**Comment by l-zeuch** [comment]
lol this has merge conflicts now :^)
Might wanna close this anyways? Looks stale to me...

**Comment by BlackWolfWoof** [comment]
I closed this now because it is a lil bit older.
I didn't merge it before because i wanted to keep it simple and people should see that it is just simple copy pasta sooo uhhh yea CLOSED :)

**Pull request closed without merging**
