### PR TITLE
mistake in dbkey???

### PR DESCRIPTION
**Pull request by Piterxyz**
Just saw it recently and I guess it's a mistake.

### CODE REVIEW

**Comment by l-zeuch** [comment]
Doesn't look like one, this converts the rather intricately formatted value to a human readable JSON format.

**Comment by Piterxyz** [comment]
Value before the change:
image

Value after:
image

¯\_(ツ)_/¯

**Comment by l-zeuch** [comment]
lolwot

**Comment by BlackWolfWoof** [comment]
Nop, no mistake. It should output as json so it is more readable _if for example you have a map / sdict_

**Pull request closed without merging**
