### PR TITLE
Update dball.yag to use (printf "%+v") not json.

### PR DESCRIPTION
**Pull request by Hyakki999**

### CODE REVIEW

**Comment by l-zeuch** [comment]
From the [Go docs](https://pkg.go.dev/fmt#hdr-Printing)
> ```
> %v    the value in a default format
>       when printing structs, the plus flag (%+v) adds field names
> ```

**Comment by l-zeuch** [comment]
Though I don't quite see the benefit here -- what makes `printf %+v` preferable over `json`?
`%+v` formats it in a Go-syntax manner, which is often more confusing. JSON is specifically made to be easily readable. Plus, `%+v` does not  show the type of the values, as per the following screenshot:
json vs printf
For what it's worth, the numbers in this example could very well be strings, which is shown by using JSON:
json showing type

All in all, if this is mainly due to a performance boost, it's not worth it, as some information is lost.

**Comment by Hyakki999** [comment]
That is the only workaround I could think of to make it show dict values.

**Comment by Hyakki999** [comment]
Ok

**Pull request closed without merging**
