### PR TITLE
Update Wall of Shame

### PR DESCRIPTION
**Pull request by YeetusBaboon**
Can't believe people do this tbh

### CODE REVIEW

**Comment by BlackWolfWoof** [comment]
Wait that cunt renamed themselfs?

**Comment by BlackWolfWoof** [comment]
*nice person

**Comment by YeetusBaboon** [comment]
Yup

**Comment by BlackWolfWoof** [comment]
Discusting

**Comment by YeetusBaboon** [comment]
absolutely

**Comment by BlackWolfWoof** [comment]
Ty for the pr m8

**Pull request merged**
