### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ryanalexander**
Added Syrus bot to list of bots which provide a faster way to catch new phishing links

### CODE REVIEW

**Comment by BlackWolfWoof** [comment]
Bot does not use an up to date api with Phishing links

**Comment by ryanalexander** [comment]
Yes it does? Uses its own api...

This bot currently protects multiple servers with 10k+ members

**Comment by BlackWolfWoof** [comment]
Awooo D3zWCpnLkD
Awooo QzzaddLfx6
Several days old phishing domain... and it doesn't get detected

**Comment by ryanalexander** [comment]
That site is no longer a nitro scam site. It was picked up when it was active

**Comment by BlackWolfWoof** [comment]
And what about steamstorehistory[.]xyz, boostnltro[.]com or discordn[.]com?
Awooo fHpcDws3cN
I am sorry but i am not gonna add that bot into my list as it doesn't even pick up any domain that has already been flagged as phishing by all the other bots in the last few days.

As you see I first picked it up on 04.11.2021 and it is still active
Awooo DwfTfkwcWb
and not being picked up by Syrus.

**Pull request closed without merging**
